spring:
  profiles: development
  data:
    mongodb:
      database: yams
      host: localhost
      port: 27017
    rest:
      base-path: /api

---

spring:
  profiles: test
  data:
    mongodb:
      database: yams-test
      host: localhost
      port: 27017
    rest:
      base-path: /api

---

spring:
  profiles: production
  data:
    rest:
      base-path: /api
    mongodb:
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      host: ${MONGO_HOST}